#=================================================
# Copyright (c) 2019-2023 sky2016cn
# Author: sky2016cn
# licensed under the MIT License
# See /LICENSE for more information
# Description: Build OpenWrt using GitHub Actions
#=================================================

name: block_Build_ax6000_immortalwrt_110m

# Add a button to trigger the workflow
on: 
  repository_dispatch:
  workflow_dispatch:

  #schedule:
    # UTC 时间对应北京时间（UTC+8=北京时间）：7月20日，早上5点10分 开始编译
    #- cron: '10 21 19 7 *'  
    # UTC 时间对应北京时间：每月2、9、16、23日，早上5点10分 开始编译    
    #- cron: '10 21 1,8,15,22 * *'
    
jobs:
  build:
    # 建议 immortalwrt 使用低版本，更容易编译成功
    runs-on: ubuntu-22.04

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        temp-reserve-mb: 512
        swap-size-mb: 2048
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        overprovision-lvm: 'true'
        build-mount-path: '/builder'        

    - name: Prepare Builder Directory
      run: |
        sudo mkdir -p /builder
        sudo chown -R runner:runner /builder
        df -hT

    - name: Checkout repository
      uses: actions/checkout@v7        

    # 如果“Initialization environment”报错，是因为官方 APT 设置依赖项的脚本已经不合时宜，在官方修正之前，请使用下方的代码
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo rm -rf /etc/apt/sources.list.d/* /usr/local/lib/android /opt/ghc /usr/share/dotnet /usr/local/graalvm /usr/local/.ghcup \
        /usr/local/share/powershell /usr/local/share/chromium /usr/local/lib/node_modules
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo chown $USER:$GROUPS $GITHUB_WORKSPACE

    # 使用此代码前，请先更新依赖包的命令：https://github.com/sky2016cn/AutoBuild-lede（依赖包仓库） 
    #- name: Initialization environment
    #  env:
    #    DEBIAN_FRONTEND: noninteractive
    #  run: |  
    #    sudo -E apt-get -qq update
    #    sudo -E apt-get -qq install $(curl -fsSL raw.githubusercontent.com/sky2016cn/OpenWrt-Depends/main/depends-immortalwrt)
    #    sudo -E apt-get -qq autoremove --purge
    #    sudo -E apt-get -qq clean
    #    sudo rm -rf /etc/apt/sources.list.d/* /usr/local/lib/android /opt/ghc /usr/share/dotnet /usr/local/graalvm /usr/local/.ghcup \
    #    /usr/local/share/powershell /usr/local/share/chromium /usr/local/lib/node_modules
    #    sudo timedatectl set-timezone "Asia/Shanghai"
    #    sudo chown $USER:$GROUPS $GITHUB_WORKSPACE
        
    - name: Check Space
      run: |
        df -h

       # ========= 1. 下载 immortalwrt 官方稳定版 v24.10.6 压缩包，发布日期：2026-04-26 ========= 
    - name: Download ImmortalWrt v24.10.6 source
      working-directory: /builder
      run: |
        # 在 tags 中查询稳定版本压缩包：https://github.com/immortalwrt/immortalwrt/tags
        # 下载源码 v24.10.6 压缩包并解压缩，会自动删除压缩包，命令末尾：v24.10.6.tar.gz，可改成你要的稳定版本号，例如：v25.12.1.tar.gz
        curl -fsSL https://github.com/immortalwrt/immortalwrt/archive/refs/tags/v24.10.6.tar.gz | tar -xz

        # 注意：解压缩后的文件夹名称中不带“v”，修改文件夹名称为“openwrt”
        mv immortalwrt-24.10.6 openwrt

       # ========= 2. 添加 immortalwrt 110m 大分区代码 =========
    - name: Apply AX6000 110M Layout Modifications
      working-directory: /builder/openwrt
      run: |
        # 1. 在 filogic.mk 末尾追加 Device（红米AX6000 设备定义）
        cat << 'EOF' >> target/linux/mediatek/image/filogic.mk

        define Device/xiaomi_redmi-router-ax6000-110m
          $(Device/xiaomi_redmi-router-ax6000-stock)
          DEVICE_VARIANT := (hanwckf 110M layout)
          DEVICE_DTS := mt7986a-xiaomi-redmi-router-ax6000-110m
          SUPPORTED_DEVICES := xiaomi,redmi-router-ax6000
          IMAGE_SIZE := 112640k
          KERNEL_IN_UBI := 1
          IMAGES := factory.bin sysupgrade.bin
          IMAGE/factory.bin := append-ubi | check-size $$$$(IMAGE_SIZE)
          IMAGE/sysupgrade.bin := sysupgrade-tar | append-metadata
        endef
        TARGET_DEVICES += xiaomi_redmi-router-ax6000-110m
        EOF

        # 2. 创建全新的 immortalwrt 110m大分区 DTS 设备树文件
        cat << 'EOF' > target/linux/mediatek/dts/mt7986a-xiaomi-redmi-router-ax6000-110m.dts
        // SPDX-License-Identifier: (GPL-2.0 OR MIT)

        /dts-v1/;
        #include "mt7986a-xiaomi-redmi-router-ax6000.dtsi"

        / {
        	model = "Xiaomi Redmi Router AX6000 (hanwckf 110M layout)";
        	compatible = "xiaomi,redmi-router-ax6000", "mediatek,mt7986a";
        };

        &spi_nand_flash {
        	mediatek,nmbm;
        	mediatek,bmt-max-ratio = <1>;
        	mediatek,bmt-max-reserved-blocks = <64>;
        };

        &partitions {
        	partition@580000 {
        		label = "crash";
        		reg = <0x580000 0x40000>;
        		read-only;
        	};

        	partition@5c0000 {
        		label = "crash_log";
        		reg = <0x5c0000 0x40000>;
        		read-only;
        	};

        	partition@600000 {
        		label = "ubi";
        		reg = <0x600000 0x6e00000>;
        	};
        };
        EOF

        echo "✅ AX6000 110M 大分区适配代码补丁应用成功！"

    - name: Add Locked OpenClash & Passwall
      working-directory: /builder/openwrt	
      run: |
        # ======== 编译 OpenClash 锁定版（v0.47.111）=========   
        #锁定 OpenClash 源码日期：2026-07-04
        sed -i '1i src-git openclash https://github.com/vernesong/OpenClash.git^bc4d118c2950f7753c2206e2e18515230b570491' ./feeds.conf.default

        # ======== 编译 passwall 锁定版（v26.7.1）=========                
        #锁定 passwall 的luci 和 packages 源码日期：2026-07-01
        sed -i '1i src-git passwall_luci https://github.com/Openwrt-Passwall/openwrt-passwall.git^59024567efc118e281697be064d881433e1b9e5f' ./feeds.conf.default
        sed -i '1i src-git passwall_packages https://github.com/Openwrt-Passwall/openwrt-passwall-packages.git^3be1c8ac62561a55d6a7033a95185f8e6df4733e' ./feeds.conf.default
        
    - name: Update feeds
      working-directory: /builder/openwrt
      run: |
        ./scripts/feeds update -a        

    - name: Install feeds
      working-directory: /builder/openwrt
      run: |
        ./scripts/feeds install -a

    - name: Install feeds
      working-directory: /builder/openwrt
      run: |
        ./scripts/feeds install -a     
                
    - name: Configuration Customization - Build_ax6000_immortalwrt_110m
      env:
        CONFIG_FILE: 'ax6000_immortalwrt_110m.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE /builder/openwrt/.config
        chmod +x ./customize_immortalwrt.sh && ./customize_immortalwrt.sh
        cd /builder/openwrt && make defconfig

    - name: Download package
      working-directory: /builder/openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build firmware
      working-directory: /builder/openwrt
      run: |
        echo -e "$(nproc) thread build."
        # 先尝试多线程全速编译，如果失败（返回非 0 状态码），则触发单线程编译，并打印最详细的 V=s 日志
        make -j$(nproc) || make -j1 V=s

    - name: Check Space
      run: |
        df -h
        
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: ax6000_immortalwrt
        path: /builder/openwrt/bin
