#=================================================
# Copyright (c) 2019-2023 sky2016cn
# Author: sky2016cn
# licensed under the MIT License
# See /LICENSE for more information
# Description: Build OpenWrt using GitHub Actions
#=================================================

name: block_Build_ax6000_LEDE_110m

# Add a button to trigger the workflow
on: 
  repository_dispatch:
  workflow_dispatch:

  #schedule:
    # UTC 时间对应北京时间（UTC+8=北京时间）：7月20日，早上5点10分 开始编译
    #- cron: '10 21 19 7 *'  
    # UTC 时间对应北京时间：每月2、9、16、23日，早上5点10分 开始编译    
    #- cron: '10 21 1,8,15,22 * *'
    
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        temp-reserve-mb: 512
        swap-size-mb: 2048
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        overprovision-lvm: 'true'
        build-mount-path: '/builder'        

    - name: Prepare Builder Directory
      run: |
        sudo mkdir -p /builder
        sudo chown -R runner:runner /builder
        df -hT

    - name: Checkout repository
      uses: actions/checkout@v7        

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        # 1. 编译前，必须更新安装依赖包命令，请到 sky2016cn/OpenWrt-Depends 仓库：https://github.com/sky2016cn/OpenWrt-Depends/actions/workflows/update_dependency_LEDE.yml，运行一次"Run workflow"
        echo "=== 开始安装 OpenWrt 编译依赖 ==="
        curl -fsSL https://raw.githubusercontent.com/sky2016cn/OpenWrt-Depends/main/depends-lede | sudo bash
                
        # 2. 清理系统无用软件包，释放磁盘空间
        echo "=== 正在清理临时文件和无用缓存 ==="
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo rm -rf /etc/apt/sources.list.d/* /usr/local/lib/android /opt/ghc /usr/share/dotnet /usr/local/graalvm /usr/local/.ghcup \
        /usr/local/share/powershell /usr/local/share/chromium /usr/local/lib/node_modules
        
        # 3. 设置时区并修正工作区权限
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo chown $USER:$GROUPS $GITHUB_WORKSPACE
        echo "✅ 环境初始化完毕！"

    - name: Check Space
      run: |
        df -h
        
       # # ========= 下载 LEDE 官方稳定版 20251001 压缩包，发布日期：2025-10-01 =========
    - name: Download LEDE 20251001 source
      working-directory: /builder
      run: |
        # 在 tags 中查询稳定版本压缩包：https://github.com/coolsnowwolf/lede/tags
        # 下载源码 20251001 压缩包并解压缩，会自动删除压缩包，命令末尾：20251001.tar.gz，可改成你要的稳定版
        curl -fsSL https://github.com/coolsnowwolf/lede/archive/refs/tags/20251001.tar.gz | tar -xz

        # 注意：修改文件夹名称为“openwrt”
        mv lede-20251001 openwrt

    - name: Add Locked OpenClash & Passwall
      working-directory: /builder/immortalwrt	
      run: |
        # ======== 编译 OpenClash 锁定版（v0.47.111）=========   
        #锁定 OpenClash 源码日期：2026-07-04
        sed -i '1i src-git openclash https://github.com/vernesong/OpenClash.git^bc4d118c2950f7753c2206e2e18515230b570491' ./feeds.conf.default

        # ======== 编译 passwall 锁定版（v26.7.1）=========                
        #锁定 passwall 的luci 和 packages 源码日期：2026-07-01
        sed -i '1i src-git passwall_luci https://github.com/Openwrt-Passwall/openwrt-passwall.git^59024567efc118e281697be064d881433e1b9e5f' ./feeds.conf.default
        sed -i '1i src-git passwall_packages https://github.com/Openwrt-Passwall/openwrt-passwall-packages.git^3be1c8ac62561a55d6a7033a95185f8e6df4733e' ./feeds.conf.default
                  
    - name: Update feeds
      working-directory: /builder/openwrt
      run: |
        ./scripts/feeds update -a     

    - name: Install feeds
      working-directory: /builder/openwrt
      run: |
        ./scripts/feeds install -a

    - name: Install feeds
      working-directory: /builder/openwrt
      run: |
        ./scripts/feeds install -a

    - name: Configuration Customization - block_Build_ax6000_LEDE_110m
      env:
        CONFIG_FILE: 'ax6000_LEDE_110m.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE /builder/openwrt/.config
        chmod +x ./customize.sh && ./customize.sh
        cd /builder/openwrt && make defconfig
        
    - name: Download package
      working-directory: /builder/openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build firmware
      working-directory: /builder/openwrt
      run: |
        echo -e "$(nproc) thread build."
        # 先尝试多线程全速编译，如果失败（返回非 0 状态码），则触发单线程编译，并打印最详细的 V=s 日志
        make -j$(nproc) || make -j1 V=s

    - name: Check Space
      run: |
        df -h
        
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: ax6000
        path: /builder/openwrt/bin
